name: visionfive
base: core20
version: '0.1'
summary: A gadget snap to boot VisionFive RISC-V boards from SD card
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: stable
confinement: strict
type: gadget

architectures:
  - build-on: amd64
    run-on: riscv64

parts:
  u-boot:
    source: .
    plugin: nil
    override-build: |
      touch $SNAPCRAFT_PART_INSTALL/uboot.conf
      mkenvimage -r -s 4096 -o $SNAPCRAFT_PART_INSTALL/boot.sel - < /dev/null
      cp uEnv.txt $SNAPCRAFT_PART_INSTALL/
      mkimage -A riscv -O linux -T script -C none -n "boot script" -d bootscript.txt $SNAPCRAFT_PART_INSTALL/boot.scr
    build-packages:
      - u-boot-tools
